### PR TITLE
Add test case soccer

### PR DESCRIPTION
**Pull request by Nek-**
Hello,

I like this example so I added it to your implementation of box2d :) . It is heavily inspired by the example of PlanckJS.

test it here: https://cdn.rawgit.com/Nek-/box2d.ts/feature%2Fadd-soccer/Box2D/Testbed/index.html

Feel free to merge !

### CODE REVIEW

**Comment by Nek-** [comment]
@flyover want me to rebase this MR or you don't want more tests?

**Comment by flyover** [comment]
Go ahead and rebase this.  Could you add it after the TopdownCar test please?

**Comment by Nek-** [comment]
@flyover rebased.

**Comment by flyover** [comment]
I might skip this one.  Maybe if it had controls, scoring, etc.

**Pull request closed without merging**
