### PR TITLE
re-format b2Math.js

### PR DESCRIPTION
**Pull request by finscn**
* better format of function
* ~~remove useless code in function~~
* add some more obvious comment-character for separating math Classes.

### CODE REVIEW

**Comment by flyover** [comment]
I agree the longer formatted functions are easier to read.  I'll change that.  However, you have to be careful removing the temp variables in the cross product functions.  If the input and the output are the same object, the x property would be overwritten before it's used.

**Comment by finscn** [comment]
I see.  thanks for your reminding

**Comment by finscn** [comment]
Hi @flyover , I've fix the bug of the cross product functions in this PR.
I think you could merge this one.

**Comment by finscn** [comment]
Hi @flyover , could review this pr ?
And How do you think about that separate the math classes to different JS files ?

**Comment by flyover** [comment]
I haven't merged this because I'm still considering your recommendation of splitting the b2Math file into separate files for each class.  I have it as is because I wanted to match the original Box2D source as much as possible.

**Comment by flyover** [comment]
Thanks for the effort, but I think I'm going to skip this one.

**Pull request closed without merging**
